# Generated by Django 2.2.6 on 2019-10-27 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('conteudo', tinymce.models.HTMLField()),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'RASCUNHO'), (1, 'PUBLICADO')], default=0)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_postagens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
